### ISSUE TITLE
Only set `exports.cryptographic` to a boolean

### ISSUE THREAD

**Issue by Richienb** [michaelrhodes/math-random#8]
Right now, `exports.cryptographic` may be set to `true` or `undefined`. To simplify things, it should just be set to `true` or `false`.

// @michaelrhodes

**Comment by Richienb** [comment]
@michaelrhodes ^

**Comment by michaelrhodes** [comment]
This has been addressed in `2.0.0`. The reason that value wasn’t strictly boolean was because I didn’t feel comfortable mutating the native `Math.random` object. That said, your ping inspired me to refactor the module, removing some unnecessary feature detection in the browser version, and replacing the `cryptographic` property with `math-random/is-secure`, a submodule that always exports a boolean :)
